# Generated by Django 5.2.1 on 2025-05-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthstatus',
            old_name='light',
            new_name='moisture',
        ),
    ]
